FROM python:3

RUN mkdir -p /app/server
WORKDIR /app/server

COPY requirements.txt /app/server/requirements.txt
RUN pip install -r /app/server/requirements.txt

COPY . /app/server

ENTRYPOINT ["sh", "-c", "uwsgi --ini /app/server/config/uwsgi.ini"]