FROM python:3

RUN mkdir -p /app/server
WORKDIR /app/server

COPY requirements.txt /app/server/requirements.txt
RUN pip install -r /app/server/requirements.txt

COPY . /app/server

CMD ["uwsgi", '--init', './config/uwsgi.ini']